# See https://www.git-town.com/configuration-file for details

[branches]
main = "main"
order = "asc"

[create]
new-branch-type = "feature"
share-new-branches = "push"
stash = true

[hosting]
forge-type = "github"

[ship]
delete-tracking-branch = false
strategy = "api"

[sync]
auto-sync = true
feature-strategy = "merge"
perennial-strategy = "rebase"
prototype-strategy = "merge"
push-branches = true
push-hook = true
tags = false
upstream = true
